version: '3.9'
services:
    app:
        restart: always
        container_name: yassir-apis
        init: true
        build:
            context: ./
            target: development
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - '3000:3000'
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        image: postgres:15.2
        container_name: yassir-postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            PGDATA: /data/postgres
        volumes:
            - /data/postgres:/data/postgres
        ports:
            - '5432:5432'
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin"]
            interval: 5s
            timeout: 5s
            retries: 5